#!/bin/sh
# Thin shims that run developer tools inside the `dev` toolbox container.
#
# Agents and scripts on the Silverblue host call `cargo`, `rg`, `just`, etc.
# directly and know nothing about toolbox. Each shim written by this script
# turns e.g. `rg foo` on the host into `toolbox run -c dev -- rg foo`, run in
# the same cwd.
#
# usage: install.sh [-c CONTAINER] [-d DEST] [--prune] [--dry-run] [bins.list]
#   -c CONTAINER  container to target (default: dev)
#   -d DEST       directory for the shims
#                 (default: ${XDG_BIN_HOME:-$HOME/.local/bin})
#   --prune       remove generated shims in DEST that are no longer listed
#   --dry-run     print what would be written/removed, change nothing
#   bins.list     binary list, one name per line, '#' starts a comment
#                 (default: bins.list next to this script)
#
# Only files carrying the "generated by workstation-config" marker are ever
# overwritten or pruned; anything else in DEST is left untouched.
#
# Behaviour of the generated shims (from toolbox src/cmd/run.go and
# src/pkg/utils/utils.go):
# - `toolbox run` preserves the cwd and propagates the tool's exit status,
#   with one upstream wart: toolbox 0.3 reports success when the tool itself
#   exits 127 (it assumes "command not found" was its own doing).
# - stdin/stdout/stderr and a TTY pass through, so interactive tools work.
# - toolbox forwards only an allowlist of host env vars: COLORTERM, DISPLAY,
#   HOME, HIST*, LANG, SHELL, SSH_AUTH_SOCK, TERM, WAYLAND_DISPLAY,
#   XAUTHORITY, and the XDG_* variables. `FOO=1 rg ...` on the host does NOT
#   make FOO visible to the tool; EDITOR and other variables outside the
#   allowlist are not forwarded either.
# - if the host cwd is not visible inside the container (anything outside
#   $HOME, e.g. /tmp or /mnt), toolbox falls back to $HOME with a notice on
#   stderr, so these shims are only reliable under $HOME.
# - the tool sees argv[0] as its container path, so multi-call binaries need
#   one shim per name — hence one line per name in bins.list.

set -eu

CONTAINER=dev
DEST=${XDG_BIN_HOME:-"$HOME/.local/bin"}
SCRIPT_DIR=$(CDPATH='' cd "$(dirname -- "$0")" && pwd)
LIST=$SCRIPT_DIR/bins.list
DRY_RUN=0
PRUNE=0
MARKER='generated by workstation-config'
written=0
skipped=0
removed=0
seen=

warn() {
  printf 'install.sh: warning: %s\n' "$1" >&2
}

die() {
  printf 'install.sh: error: %s\n' "$1" >&2
  exit "${2:-1}"
}

usage() {
  cat <<'EOF'
usage: install.sh [-c CONTAINER] [-d DEST] [--prune] [--dry-run] [bins.list]

  -c CONTAINER  container to target (default: dev)
  -d DEST       directory for the shims (default: ${XDG_BIN_HOME:-$HOME/.local/bin})
  --prune       remove generated shims no longer listed
  --dry-run     print what would be written/removed, change nothing
  bins.list     binary list (default: bins.list next to this script)
EOF
}

exists() {
  [ -e "$1" ] || [ -L "$1" ]
}

# listed NAME: is NAME one of the entries in $bins?
listed() {
  # shellcheck disable=SC2086  # entries contain no whitespace or globs
  for entry in $bins; do
    if [ "$entry" = "$1" ]; then
      return 0
    fi
  done
  return 1
}

while [ $# -gt 0 ]; do
  case $1 in
    -c)
      [ $# -ge 2 ] || die 'option -c requires an argument' 2
      CONTAINER=$2
      shift 2
      ;;
    -d)
      [ $# -ge 2 ] || die 'option -d requires an argument' 2
      DEST=$2
      shift 2
      ;;
    --prune)
      PRUNE=1
      shift
      ;;
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    -h | --help)
      usage
      exit 0
      ;;
    --)
      shift
      break
      ;;
    -*)
      usage >&2
      die "unknown option: $1" 2
      ;;
    *)
      break
      ;;
  esac
done

if [ $# -gt 1 ]; then
  usage >&2
  die 'too many arguments' 2
fi
if [ $# -eq 1 ]; then
  LIST=$1
fi

# The name is interpolated into generated shell; keep it to podman's own
# container-name alphabet so it can never be read as syntax.
case $CONTAINER in
  '' | *[!A-Za-z0-9._-]*) die "invalid container name: '$CONTAINER'" 2 ;;
esac
[ -r "$LIST" ] || die "cannot read binary list: $LIST"

# Normalize: strip comments and all whitespace, keep nonempty lines only.
bins=$(sed -e 's/#.*//' -e 's/[[:space:]]//g' "$LIST" | grep -v '^$' || true)
# An empty list is only meaningful with --prune (remove every shim).
if [ -z "$bins" ] && [ "$PRUNE" -eq 0 ]; then
  die "no binary names in $LIST"
fi

case :$PATH: in
  *":$DEST:"*) ;;
  *) warn "$DEST is not in \$PATH; shims there will not be found by name" ;;
esac

if [ "$DRY_RUN" -eq 0 ]; then
  mkdir -p "$DEST"
fi

# Word-split $bins without pathname expansion: a stray '*' in the list must
# be rejected by the validation below, not globbed into DEST's contents.
set -f
# shellcheck disable=SC2086  # normalized entries contain no whitespace
for bin in $bins; do
  case $bin in
    '' | .* | *[!A-Za-z0-9._+-]*)
      warn "skipping invalid binary name '$bin' in $LIST"
      continue
      ;;
  esac
  case ",$seen," in
    *",$bin,"*)
      warn "ignoring duplicate entry '$bin' in $LIST"
      continue
      ;;
  esac
  seen="$seen,$bin"
  target=$DEST/$bin
  # A symlink is never ours, even if its target carries the marker: writing
  # through it would modify a file outside DEST.
  if [ -L "$target" ] || { exists "$target" && ! grep -qF -- "$MARKER" "$target" 2>/dev/null; }; then
    warn "skipping $target: exists and was not generated by this script"
    skipped=$((skipped + 1))
    continue
  fi
  if [ "$DRY_RUN" -eq 1 ]; then
    printf 'would write %s\n' "$target"
    written=$((written + 1))
    continue
  fi
  cat >"$target" <<EOF
#!/bin/sh
# $MARKER/toolbox/shims/install.sh — do not edit
exec toolbox run -c '$CONTAINER' -- '$bin' "\$@"
EOF
  chmod 0755 "$target"
  printf 'wrote %s\n' "$target"
  written=$((written + 1))
done
set +f

if [ "$PRUNE" -eq 1 ]; then
  for file in "$DEST"/*; do
    if [ -L "$file" ] || ! grep -qF -- "$MARKER" "$file" 2>/dev/null; then
      continue
    fi
    name=${file##*/}
    if listed "$name"; then
      continue
    fi
    if [ "$DRY_RUN" -eq 1 ]; then
      printf 'would remove %s\n' "$file"
    else
      rm -f "$file"
      printf 'removed %s\n' "$file"
    fi
    removed=$((removed + 1))
  done
fi

printf '%d written, %d skipped, %d removed\n' "$written" "$skipped" "$removed"
